# src/trainer/unlearn/nova.py
import torch
from torch import nn
import logging
from trainer.unlearn.base import UnlearnTrainer
from torch.nn import functional as F

import data.nova_speedup

# NOVA (Noise-Optimized Vector for Annulling)
# 
# Inspiration from 
# https://github.com/vikram2000b/Fast-Machine-Unlearning
# Extended in
# https://github.com/MoraiT01/study_on_unlearning # Here the algorithms, which follow these same principles, are refered to as GeFeU, FEMU and FEMU+

logger = logging.getLogger(__name__)

class AntiPattern(nn.Module):
    def __init__(self, batch_size: int, seq_len: int, embedding_dim: int, attention_mask: torch.Tensor = None): # type: ignore
        super().__init__()
        # The core learned anti-pattern: initialized randomly with batch_size, seq_len, embedding_dim.
        # This parameter represents the direct perturbation for the input sequence, acting as a replacement for original embeddings.
        self.pattern = torch.nn.Parameter(torch.randn((batch_size, seq_len, embedding_dim)), requires_grad = True)
        self.mask = attention_mask.clone() if attention_mask is not None else None # Store mask as part of the instance

    def forward(self,):
        # Apply attention mask to the learned pattern
        if self.mask is not None:
            # Unsqueeze attention_mask to (batch_size, seq_len, 1) to enable broadcasting
            masked_pattern = self.pattern * self.mask.unsqueeze(-1)
            return masked_pattern
        return self.pattern

class NOVA(UnlearnTrainer):
    def __init__(self, 
                 noise_epochs: int = 10, 
                 noise_lr: float = 0.0001,
                 regularization_term: float = 0.0001,
                 alpha: float = 0.001,
                 sign: int = 1,
                 soft_target: bool = False,
                 *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.noise_epochs = noise_epochs
        self.noise_lr = noise_lr
        self.regularization_term = regularization_term
        self.alpha = alpha
        self.sign = sign
        self.soft_target = soft_target
        logger.info(f"NOVA initialized with: n_epochs {self.noise_epochs}| n_lr {self.noise_lr}| reg_term {self.regularization_term}| alpha {self.alpha}| sign {self.sign}| soft {self.soft_target}")
        # Initialize KLDivLoss for soft targets
        self.kl_loss_fct = nn.KLDivLoss(reduction='batchmean') # Use 'batchmean' or 'sum' as appropriate

        self.model_name = None

    def get_soft_target(self, model: nn.Module, forget_inputs: dict) -> torch.Tensor:
        """
        Generates soft targets (logits) for the forget inputs by passing them
        through the current model. These logits can be used as targets
        for a knowledge distillation-like loss to guide unlearning.

        Args:
            model (nn.Module): The model used to generate the soft targets.
            forget_inputs (dict): A dictionary containing 'input_ids' and 'attention_mask'
                                  for the forget set. Labels are NOT used for target generation.

        Returns:
            torch.Tensor: The logits generated by the model for the forget inputs,
                          to be used as soft targets. Shape: (batch_size, sequence_length, vocab_size).
        """
        original_training_state = model.training
        model.eval() # Ensure the model is in eval mode for consistent output without dropout/batchnorm effects
        
        with torch.no_grad(): # No gradients needed for target generation
            outputs = model(
                input_ids=forget_inputs["input_ids"], # Use input_ids to get embeddings internally
                attention_mask=forget_inputs["attention_mask"],
                # Do NOT pass 'labels' here, as we are generating the targets
            )
        
        model.train(original_training_state) # Restore model training state

        # We need the logits to compute KL Divergence later.
        # outputs.logits will have shape (batch_size, sequence_length, vocab_size)
        return outputs.logits

    def _optimize_anti_pattern_for_batch(self, model, forget_inputs_original):
        """
        Optimizes a *new* AntiPattern for each sample in the current batch of forget_inputs.
        Each anti-pattern is trained independently.

        Args:
            model (nn.Module): The language model.
            forget_inputs_original (dict): The original forget inputs (with hard labels).

        Returns:
            torch.Tensor: The optimized perturbation tensor for the entire batch, with each sample's
                          perturbation trained independently, and then stacked together.
        """
        original_training_state = model.training
        model.eval() # Freeze the main model's parameters

        batch_size, seq_len = forget_inputs_original["input_ids"].shape
        embedding_dim = model.config.hidden_size
        all_optimized_perturbations = []

        # Iterate through each sample in the batch
        for i in range(batch_size):
            # Extract a single sample and its corresponding data
            single_forget_input = {
                key: value[i:i+1] for key, value in forget_inputs_original.items()
            }
            single_attention_mask = single_forget_input["attention_mask"].to(model.device)
            # Here we check, whether the anti-pattern has been created for this sample already.
            if data.nova_speedup.exists(
                    base_model=self.model_name,
                    noise_epochs=self.noise_epochs,
                    noise_lr=self.noise_lr,
                    reg_term=self.regularization_term,
                    soft_target=self.soft_target,
                    sample=torch.squeeze(single_forget_input["input_ids"], 0),
                ):
                logger.info(f"Matching Prior Processed Anti-pattern found!")
                all_optimized_perturbations.append(
                    data.nova_speedup.get(
                        base_model=self.model_name,
                        noise_epochs=self.noise_epochs,
                        noise_lr=self.noise_lr,
                        reg_term=self.regularization_term,
                        soft_target=self.soft_target,
                        sample=torch.squeeze(single_forget_input["input_ids"], 0),
                    )
                )
            else:
                # Create a new AntiPattern instance and optimizer for the single sample
                anti_pattern_instance = AntiPattern(
                    batch_size=1,
                    seq_len=seq_len,
                    embedding_dim=embedding_dim,
                    attention_mask=single_attention_mask
                ).to(model.device)
                optimizer_for_this_sample = torch.optim.Adam(anti_pattern_instance.parameters(), lr=self.noise_lr)

                # Prepare the target for anti-pattern optimization
                if self.soft_target:
                    ap_target = self.get_soft_target(model, single_forget_input).detach()
                    ap_labels_for_model_call = None
                else:
                    ap_target = single_forget_input["labels"].to(model.device)
                    ap_labels_for_model_call = ap_target

                with torch.enable_grad():
                    for epoch_idx in range(self.noise_epochs):
                        optimizer_for_this_sample.zero_grad()

                        perturbation = anti_pattern_instance()

                        model_outputs = model(
                            inputs_embeds=perturbation,
                            attention_mask=single_attention_mask,
                            labels=ap_labels_for_model_call
                        )

                        if self.soft_target:
                            log_softmax_model_outputs = F.log_softmax(model_outputs.logits, dim=-1)
                            softmax_soft_targets = F.softmax(ap_target, dim=-1)
                            kl_loss = -self.kl_loss_fct(log_softmax_model_outputs, softmax_soft_targets)
                            anti_pattern_loss = kl_loss
                        else:
                            anti_pattern_loss = -model_outputs.loss

                        # Add regularization term
                        anti_pattern_loss += self.regularization_term * torch.mean(torch.square(perturbation.detach()))

                        anti_pattern_loss.backward()
                        optimizer_for_this_sample.step()

                        if (epoch_idx + 1) % max(1, self.noise_epochs // 5) == 0:
                            logger.info(f"Sample {i+1}/{batch_size}, Anti-pattern Epoch {epoch_idx+1}/{self.noise_epochs}, Current Loss: {anti_pattern_loss.item():.4f}")
                        
                # Save the optimized perturbation for this sample
                logger.info(f"Saving created Anti-pattern for later Use")
                data.nova_speedup.put(
                    base_model=self.model_name,
                    noise_epochs=self.noise_epochs,
                    noise_lr=self.noise_lr,
                    reg_term=self.regularization_term,
                    soft_target=self.soft_target,
                    key=torch.squeeze(single_forget_input["input_ids"], 0),
                    value=anti_pattern_instance.pattern.detach(),
                )

                all_optimized_perturbations.append(anti_pattern_instance.pattern.detach())
                logger.info(f"Sample {i+1}/{batch_size} Anti-pattern Training done; Final Loss: {anti_pattern_loss.item():.4f}")

        model.train(original_training_state)
        return torch.cat(all_optimized_perturbations, dim=0)

    def compute_intermediate_loss(self, model: nn.Module, inputs: dict, uses_embeds: bool = False, soft_targets_for_loss: torch.Tensor | None = None):
        """
        Computes the loss for a given set of inputs.
        
        Args:
            model (nn.Module): The language model.
            inputs (dict): Dictionary containing 'input_ids', 'attention_mask', and 'labels'.
                           'input_ids' can be raw token IDs or embeddings if uses_embeds is True.
            uses_embeds (bool): If True, 'input_ids' in inputs are treated as embeddings.
            soft_targets_for_loss (torch.Tensor, optional): If provided, computes KL Divergence
                                                            between model's logits and these soft targets.
                                                            Otherwise, uses CrossEntropyLoss with hard labels.
        Returns:
            Tuple[torch.Tensor, Any]: The computed loss and the model's outputs.
        """
        if uses_embeds:
            # When inputs_embeds are used, labels are NOT directly passed to model if we want to
            # compute custom loss like KL divergence with soft targets.
            model_outputs = model(
                inputs_embeds=inputs["input_ids"], # This is the optimized perturbation
                attention_mask=inputs["attention_mask"],
                labels=None # Crucially, do not pass labels if we're doing a custom loss
            )
        else:
            # For retain data, use standard forward pass with input_ids and hard labels
            model_outputs = model(**inputs)
        
        loss = 0.0
        if soft_targets_for_loss is not None:
            # If soft targets are provided, compute KL Divergence
            log_softmax_outputs = F.log_softmax(model_outputs.logits, dim=-1)
            softmax_soft_targets = F.softmax(soft_targets_for_loss, dim=-1)
            
            loss = self.kl_loss_fct(log_softmax_outputs, softmax_soft_targets)

        else:
            # Use the model's internal loss calculation (CrossEntropyLoss for CausalLM)
            if "labels" not in inputs:
                raise ValueError("Labels must be provided for hard target loss computation.")
            
            # Re-call the model with labels to get its internal loss
            model_outputs_with_labels = model(
                input_ids=inputs["input_ids"] if not uses_embeds else None,
                inputs_embeds=inputs["input_ids"] if uses_embeds else None, # Pass embeddings if flag is set
                attention_mask=inputs["attention_mask"],
                labels=inputs["labels"]
            )
            loss = model_outputs_with_labels.loss
            model_outputs = model_outputs_with_labels # Update outputs to include loss

        return loss, model_outputs

    def compute_loss(self, model, inputs, return_outputs=False):
        forget_inputs = inputs["forget"]
        retain_inputs = inputs["retain"]

        if self.model_name is None:
            self.model_name = model.config._name_or_path

        # --- Phase 1: Optimize a batch-specific AntiPattern and get its output ---
        # For anti-pattern optimization, use the original hard labels.
        # This makes the anti-pattern aim to maximize the model's *original* loss.
        optimized_perturbation_for_batch = self._optimize_anti_pattern_for_batch(model, forget_inputs)

        # --- Phase 2: Main Model Unlearning Step using the optimized perturbation from Phase 1 ---
        # Get soft targets if enabled for the *main unlearning phase* (impairment of forget data)
        soft_targets_for_impairment = None
        if self.soft_target:
            # This will generate logits of shape (batch_size, seq_len, vocab_size)
            soft_targets_for_impairment = self.get_soft_target(model, forget_inputs)
            # No modification to forget_inputs["labels"] directly here,
            # we pass soft_targets_for_impairment to compute_intermediate_loss

        # The optimized_perturbation_for_batch now directly acts as the noisy input embeddings.
        final_antipattern_embeddings = optimized_perturbation_for_batch

        # --- LOGGING THE ANTI-PATTERN HERE ---
        if logger.isEnabledFor(logging.INFO) and final_antipattern_embeddings is not None:
            # Choose the same sample_idx as for input/output logging
            sample_idx = 0 
            if final_antipattern_embeddings.shape[0] > sample_idx:
                anti_pattern_sample = final_antipattern_embeddings[sample_idx] # Shape: (seq_len, embedding_dim)
                
                logger.info(f"Anti-Pattern Shape: {anti_pattern_sample.shape}")
            else:
                logger.warning(f"Anti-pattern tensor does not contain sample {sample_idx}.")
        # --- END LOGGING THE ANTI-PATTERN ---

        # Compute forget loss (using the antipatterns as the input)
        # Pass the original hard labels to forget_inputs_processed if soft_target is False,
        # otherwise pass the soft_targets_for_impairment to the loss computation.
        
        # When soft_target is True, compute_intermediate_loss will receive soft_targets_for_impairment
        # and should use KLDivLoss. It should *not* receive `labels` in `forget_inputs_processed`.
        # When soft_target is False, it will receive `labels` in `forget_inputs_processed`
        # and compute_intermediate_loss will use the model's internal CrossEntropyLoss.
        
        forget_inputs_processed ={
            "input_ids": final_antipattern_embeddings,
            "attention_mask": forget_inputs["attention_mask"],
            # Labels are only passed if soft_target is FALSE, otherwise KLDivLoss is used.
            "labels": forget_inputs["labels"] if not self.soft_target else None, 
        }
        
        forget_loss, forget_outputs = self.compute_intermediate_loss(
            model=model, 
            inputs=forget_inputs_processed, 
            uses_embeds=True,
            soft_targets_for_loss=soft_targets_for_impairment # Pass soft targets explicitly for KLDivLoss
        )

        # Compute retain loss (using standard input_ids and hard labels)
        retain_inputs_processed = {
            "input_ids": retain_inputs["input_ids"],
            "attention_mask": retain_inputs["attention_mask"],
            "labels": retain_inputs["labels"], # Retain always uses hard labels
        }
        retain_loss, retain_outputs = self.compute_intermediate_loss(model=model, inputs=retain_inputs_processed) # No soft targets for retain

        # Combine losses for the main model's update
        loss = self.sign * forget_loss + self.alpha * retain_loss
        logger.info(f"Alpha: {self.alpha:.7f} | Forget Loss: {forget_loss.item():.7f} | Sign: {self.sign} | Retain Loss: {retain_loss.item():.7f} || Final Loss: {loss.item():.7f}")

        return (loss, forget_outputs) if return_outputs else loss